// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     create_update_s3_file.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type S3FileCreatedUpdatedMetadata struct {
	Origin_application string `json:"origin_application"`

	Region string `json:"region"`

	Tracking_uuid string `json:"tracking_uuid"`
}

const S3FileCreatedUpdatedMetadataAvroCRC64Fingerprint = "\x03\x88\xb9\xbaԮ\xad9"

func NewS3FileCreatedUpdatedMetadata() S3FileCreatedUpdatedMetadata {
	r := S3FileCreatedUpdatedMetadata{}
	return r
}

func DeserializeS3FileCreatedUpdatedMetadata(r io.Reader) (S3FileCreatedUpdatedMetadata, error) {
	t := NewS3FileCreatedUpdatedMetadata()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func DeserializeS3FileCreatedUpdatedMetadataFromSchema(r io.Reader, schema string) (S3FileCreatedUpdatedMetadata, error) {
	t := NewS3FileCreatedUpdatedMetadata()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func writeS3FileCreatedUpdatedMetadata(r S3FileCreatedUpdatedMetadata, w io.Writer) error {
	var err error
	err = vm.WriteString(r.Origin_application, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.Region, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.Tracking_uuid, w)
	if err != nil {
		return err
	}
	return err
}

func (r S3FileCreatedUpdatedMetadata) Serialize(w io.Writer) error {
	return writeS3FileCreatedUpdatedMetadata(r, w)
}

func (r S3FileCreatedUpdatedMetadata) Schema() string {
	return "{\"fields\":[{\"name\":\"origin_application\",\"type\":\"string\"},{\"name\":\"region\",\"type\":\"string\"},{\"logicalType\":\"uuid\",\"name\":\"tracking_uuid\",\"type\":\"string\"}],\"name\":\"com.kidsloop.S3FileCreatedUpdatedMetadata\",\"type\":\"record\"}"
}

func (r S3FileCreatedUpdatedMetadata) SchemaName() string {
	return "com.kidsloop.S3FileCreatedUpdatedMetadata"
}

func (_ S3FileCreatedUpdatedMetadata) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ S3FileCreatedUpdatedMetadata) SetInt(v int32)       { panic("Unsupported operation") }
func (_ S3FileCreatedUpdatedMetadata) SetLong(v int64)      { panic("Unsupported operation") }
func (_ S3FileCreatedUpdatedMetadata) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ S3FileCreatedUpdatedMetadata) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ S3FileCreatedUpdatedMetadata) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ S3FileCreatedUpdatedMetadata) SetString(v string)   { panic("Unsupported operation") }
func (_ S3FileCreatedUpdatedMetadata) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *S3FileCreatedUpdatedMetadata) Get(i int) types.Field {
	switch i {
	case 0:
		w := types.String{Target: &r.Origin_application}

		return w

	case 1:
		w := types.String{Target: &r.Region}

		return w

	case 2:
		w := types.String{Target: &r.Tracking_uuid}

		return w

	}
	panic("Unknown field index")
}

func (r *S3FileCreatedUpdatedMetadata) SetDefault(i int) {
	switch i {
	}
	panic("Unknown field index")
}

func (r *S3FileCreatedUpdatedMetadata) NullField(i int) {
	switch i {
	}
	panic("Not a nullable field index")
}

func (_ S3FileCreatedUpdatedMetadata) AppendMap(key string) types.Field {
	panic("Unsupported operation")
}
func (_ S3FileCreatedUpdatedMetadata) AppendArray() types.Field { panic("Unsupported operation") }
func (_ S3FileCreatedUpdatedMetadata) HintSize(int)             { panic("Unsupported operation") }
func (_ S3FileCreatedUpdatedMetadata) Finalize()                {}

func (_ S3FileCreatedUpdatedMetadata) AvroCRC64Fingerprint() []byte {
	return []byte(S3FileCreatedUpdatedMetadataAvroCRC64Fingerprint)
}

func (r S3FileCreatedUpdatedMetadata) MarshalJSON() ([]byte, error) {
	var err error
	output := make(map[string]json.RawMessage)
	output["origin_application"], err = json.Marshal(r.Origin_application)
	if err != nil {
		return nil, err
	}
	output["region"], err = json.Marshal(r.Region)
	if err != nil {
		return nil, err
	}
	output["tracking_uuid"], err = json.Marshal(r.Tracking_uuid)
	if err != nil {
		return nil, err
	}
	return json.Marshal(output)
}

func (r *S3FileCreatedUpdatedMetadata) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}

	var val json.RawMessage
	val = func() json.RawMessage {
		if v, ok := fields["origin_application"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Origin_application); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for origin_application")
	}
	val = func() json.RawMessage {
		if v, ok := fields["region"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Region); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for region")
	}
	val = func() json.RawMessage {
		if v, ok := fields["tracking_uuid"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Tracking_uuid); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for tracking_uuid")
	}
	return nil
}
