// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     create_update_s3_file.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type S3FileCreatedUpdated struct {
	Payload S3FileCreatedUpdatedPayload `json:"payload"`

	Metadata S3FileCreatedUpdatedMetadata `json:"metadata"`
}

const S3FileCreatedUpdatedAvroCRC64Fingerprint = "\x04랇\x14iU\n"

func NewS3FileCreatedUpdated() S3FileCreatedUpdated {
	r := S3FileCreatedUpdated{}
	r.Payload = NewS3FileCreatedUpdatedPayload()

	r.Metadata = NewS3FileCreatedUpdatedMetadata()

	return r
}

func DeserializeS3FileCreatedUpdated(r io.Reader) (S3FileCreatedUpdated, error) {
	t := NewS3FileCreatedUpdated()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func DeserializeS3FileCreatedUpdatedFromSchema(r io.Reader, schema string) (S3FileCreatedUpdated, error) {
	t := NewS3FileCreatedUpdated()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func writeS3FileCreatedUpdated(r S3FileCreatedUpdated, w io.Writer) error {
	var err error
	err = writeS3FileCreatedUpdatedPayload(r.Payload, w)
	if err != nil {
		return err
	}
	err = writeS3FileCreatedUpdatedMetadata(r.Metadata, w)
	if err != nil {
		return err
	}
	return err
}

func (r S3FileCreatedUpdated) Serialize(w io.Writer) error {
	return writeS3FileCreatedUpdated(r, w)
}

func (r S3FileCreatedUpdated) Schema() string {
	return "{\"fields\":[{\"name\":\"payload\",\"type\":{\"fields\":[{\"name\":\"key\",\"type\":\"string\"},{\"name\":\"aws_region\",\"type\":\"string\"},{\"name\":\"bucket_name\",\"type\":\"string\"},{\"name\":\"content_length\",\"type\":\"long\"},{\"name\":\"content_type\",\"type\":\"string\"},{\"name\":\"operation_type\",\"type\":\"string\"}],\"name\":\"S3FileCreatedUpdatedPayload\",\"type\":\"record\"}},{\"name\":\"metadata\",\"type\":{\"fields\":[{\"name\":\"origin_application\",\"type\":\"string\"},{\"name\":\"region\",\"type\":\"string\"},{\"logicalType\":\"uuid\",\"name\":\"tracking_uuid\",\"type\":\"string\"}],\"name\":\"S3FileCreatedUpdatedMetadata\",\"type\":\"record\"}}],\"name\":\"com.kidsloop.S3FileCreatedUpdated\",\"type\":\"record\"}"
}

func (r S3FileCreatedUpdated) SchemaName() string {
	return "com.kidsloop.S3FileCreatedUpdated"
}

func (_ S3FileCreatedUpdated) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ S3FileCreatedUpdated) SetInt(v int32)       { panic("Unsupported operation") }
func (_ S3FileCreatedUpdated) SetLong(v int64)      { panic("Unsupported operation") }
func (_ S3FileCreatedUpdated) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ S3FileCreatedUpdated) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ S3FileCreatedUpdated) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ S3FileCreatedUpdated) SetString(v string)   { panic("Unsupported operation") }
func (_ S3FileCreatedUpdated) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *S3FileCreatedUpdated) Get(i int) types.Field {
	switch i {
	case 0:
		r.Payload = NewS3FileCreatedUpdatedPayload()

		w := types.Record{Target: &r.Payload}

		return w

	case 1:
		r.Metadata = NewS3FileCreatedUpdatedMetadata()

		w := types.Record{Target: &r.Metadata}

		return w

	}
	panic("Unknown field index")
}

func (r *S3FileCreatedUpdated) SetDefault(i int) {
	switch i {
	}
	panic("Unknown field index")
}

func (r *S3FileCreatedUpdated) NullField(i int) {
	switch i {
	}
	panic("Not a nullable field index")
}

func (_ S3FileCreatedUpdated) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ S3FileCreatedUpdated) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ S3FileCreatedUpdated) HintSize(int)                     { panic("Unsupported operation") }
func (_ S3FileCreatedUpdated) Finalize()                        {}

func (_ S3FileCreatedUpdated) AvroCRC64Fingerprint() []byte {
	return []byte(S3FileCreatedUpdatedAvroCRC64Fingerprint)
}

func (r S3FileCreatedUpdated) MarshalJSON() ([]byte, error) {
	var err error
	output := make(map[string]json.RawMessage)
	output["payload"], err = json.Marshal(r.Payload)
	if err != nil {
		return nil, err
	}
	output["metadata"], err = json.Marshal(r.Metadata)
	if err != nil {
		return nil, err
	}
	return json.Marshal(output)
}

func (r *S3FileCreatedUpdated) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}

	var val json.RawMessage
	val = func() json.RawMessage {
		if v, ok := fields["payload"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Payload); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for payload")
	}
	val = func() json.RawMessage {
		if v, ok := fields["metadata"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Metadata); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for metadata")
	}
	return nil
}
